name: genchi_app
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.25+101

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  firebase_core: ^1.1.0
  firebase_auth: ^1.1.0
  cloud_firestore: ^1.0.4
  firebase_storage: ^8.0.3
  firebase_crashlytics: ^2.0.0
  firebase_messaging: ^9.1.1
  firebase_performance: ^0.6.0+2
  firebase_analytics: ^7.1.1
  firebase_dynamic_links: ^0.8.0
#  firebase_remote_config: ^0.8.0-dev.0
  share: ^2.0.1
  modal_progress_hud: ^0.1.3
  image_picker: ^0.7.4
  image: ^3.0.2
  image_cropper: ^1.2.2
  provider: ^5.0.0
  get_it: ^6.0.0
  flutter_slidable: ^0.5.4
  url_launcher: ^6.0.3
  intl: ^0.17.0
  cached_network_image: ^3.0.0
  flutter_cache_manager: ^3.0.1
  rxdart: ^0.26.0
  liquid_pull_to_refresh: ^3.0.0
  shimmer: ^1.1.1
  flutter_linkify: ^5.0.0
  package_info: ^2.0.0
  sliding_up_panel: ^1.0.2
  http: ^0.13.1
  csv: ^5.0.0
  stripe_payment: ^1.1.0
  flutter_credit_card: ^2.0.0
  webview_flutter: ^2.0.7
  dio: ^4.0.0
  js: ^0.6.3
  flutter_app_badger: ^1.2.0
  path_provider: ^2.0.2
  path: ^1.8.0



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/2.0x/
    - images/3.0x/
    - images/service_icons/
    - images/onboarding/
    - images/group_icons/

  fonts:
    - family: FuturaPT
      fonts:
        - asset: fonts/FuturaPTLight.otf
          style: normal
          weight: 300

        - asset: fonts/FuturaPTBook.otf
          style: normal
          weight: 400

        - asset: fonts/FuturaPTMedium.otf
          style: normal
          weight: 500

        - asset: fonts/FuturaPTDemi.otf
          style: normal
          weight: 600

        - asset: fonts/FuturaPTHeavy.otf
          style: normal
          weight: 700

        - asset: fonts/FuturaPTBold.otf
          style: normal
          weight: 800

        - asset: fonts/FuturaPTExtraBold.otf
          style: normal
          weight: 900